# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solutionDir: './AkkaIntro/code-dotnetcore'
  solution: './AkkaIntro/code-dotnetcore/AkkaDemo.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x' # replace this value with the version that you need for your project
    includePreviewVersions: false
    performMultiLevelLookup: true
- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    restoreDirectory: '$(solutionDir)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '$(solution) --configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'