FROM microsoft/aspnetcore-build:2.0.3

# Add the neo4j repo to the packages list
RUN wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
RUN echo 'deb http://debian.neo4j.org/repo stable/' | tee -a /etc/apt/sources.list.d/neo4j.list

# Grab the packages list & install neo4j
RUN apt-get update && apt-get install -y \
cypher-shell

COPY . /app
WORKDIR /app/api/ProjectShortName.API

RUN ["dotnet", "build"]

EXPOSE 10901/tcp

ENTRYPOINT ["sh", "/app/entrypoint.sh"]