version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/ServerlessIsMore"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/AkkaIntro/presentation"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/AkkaIntro/code"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/ElasticSearch"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/Fragile"
    update_schedule: "live"