version: "3"

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=theroot
    env_file:
      - ./db.env

  app:
    image: matomo
    restart: always
    volumes:
#     - F:\DockerData\matomo\config:/var/www/html/config
#     - F:\DockerData\matomo\logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    ports:
      - 8080:80

volumes:
  db:
  matomo:
