name: "Build / Test Presentation Code"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mdx-presentations:
    name: "MDX Presentations"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        build-location: ["./netcore-workshop-mdx"]

    steps:
      - uses: actions/checkout@v2
        name: Pull the Code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        name: Restore Packages
        working-directory: ${{ matrix.build-location }}
      - run: npm run build --if-present
        name: build
        working-directory: ${{ matrix.build-location }}

  build-presentations:
    name: "MARP Presentation"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies and Puppeteer
        working-directory: ./ServerlessIsMore-marp/presentation
        run: |
          npm ci
          sudo apt-get install libgbm-dev
          npm i puppeteer --no-save

      - name: Build Marp slide deck
        working-directory: ./ServerlessIsMore-marp/presentation
        run: |
          CHROME_PATH=$(node -e "console.log(require('puppeteer').executablePath())") npm run build
          touch ./public/.nojekyll
        env:
          # Recommend to set lang for your deck to get better rendering for Open Graph image
          LANG: en-US
