name: "Build / Test Presentation Code"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mdx-presentations:
    name: "MDX Presentations"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        build-location: ["./netcore-workshop-mdx", "./ServerlessIsMore-mdx"]

    steps:
      - uses: actions/checkout@v2
        name: Pull the Code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        name: Restore Packages
        working-directory: ${{ matrix.build-location }}
      - run: npm run build --if-present
        name: build
        working-directory: ${{ matrix.build-location }}
