name: "Build / Test Presentation Code"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  akka-intro:
    name: "Akka Intro C# Code"
    runs-on: ubuntu-latest
    env:
      SOLUTION_LOCATION: "./AkkaIntro/code/AkkaIntro.Core.sln"
    steps:
      - uses: actions/checkout@v2
        name: Pull the code
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Restore dependencies
        run: dotnet restore $SOLUTION_LOCATION
      - name: Build
        run: dotnet build --no-restore $SOLUTION_LOCATION
      - name: Test
        run: dotnet test --no-build --verbosity normal $SOLUTION_LOCATION
  mdx-presentations:
    name: "MDX Presentations"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        build-location: ["./netcore-workshop-mdx", "./ServerlessIsMore-mdx"]

    steps:
      - uses: actions/checkout@v2
        name: Pull the Code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        name: Restore Packages
        working-directory: ${{ matrix.build-location }}
      - run: npm run build --if-present
        name: build
        working-directory: ${{ matrix.build-location }}

  marp-presentations:
    name: "MARP Presentation"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies and Puppeteer
        working-directory: ./AkkaIntro/presentation-marp
        run: |
          npm ci
          sudo apt-get install libgbm-dev
          npm i puppeteer --no-save
      - name: Build Marp slide deck
        working-directory: ./AkkaIntro/presentation-marp
        run: |
          CHROME_PATH=$(node -e "console.log(require('puppeteer').executablePath())") npm run build
          touch ./public/.nojekyll
        env:
          # Recommend to set lang for your deck to get better rendering for Open Graph image
          LANG: en-US
